# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\YandexDisk\coding\Python\some_projects\maze-solver\maze_solver\qt\maze_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_DialogSetting(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(236, 183)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.height_maze = QtWidgets.QSpinBox(Dialog)
        self.height_maze.setMinimum(2)
        self.height_maze.setMaximum(1000)
        self.height_maze.setProperty("value", 2)
        self.height_maze.setObjectName("height_maze")
        self.verticalLayout.addWidget(self.height_maze)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.width_maze = QtWidgets.QSpinBox(Dialog)
        self.width_maze.setMinimum(2)
        self.width_maze.setMaximum(1000)
        self.width_maze.setObjectName("width_maze")
        self.verticalLayout.addWidget(self.width_maze)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.image_name = QtWidgets.QLineEdit(Dialog)
        self.image_name.setObjectName("image_name")
        self.verticalLayout.addWidget(self.image_name)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout.addWidget(self.ok_btn)
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings Maze"))
        self.label.setText(_translate("Dialog", "Height maze:"))
        self.label_2.setText(_translate("Dialog", "Width maze:"))
        self.label_3.setText(_translate("Dialog", "Image name"))
        self.ok_btn.setText(_translate("Dialog", "OK"))
        self.cancel_btn.setText(_translate("Dialog", "Cancel"))
