# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt\maze_generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from widgets.my_qlabel import MyQLabel

from . import resource


class Ui_MazeGenerator(QtWidgets.QMainWindow):
    """Главное окно."""
    
    getPointsClicked = QtCore.pyqtSignal(list, list)

    def setupUi(self, MazeGenerator):
        """Инициализация."""
        MazeGenerator.setObjectName("MazeGenerator")
        MazeGenerator.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MazeGenerator)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.generate_maze = QtWidgets.QToolButton(self.centralwidget)
        self.generate_maze.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/maze.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.generate_maze.setIcon(icon)
        self.generate_maze.setIconSize(QtCore.QSize(24, 24))
        self.generate_maze.setObjectName("generate_maze")
        self.verticalLayout.addWidget(self.generate_maze)
        self.save_maze = QtWidgets.QToolButton(self.centralwidget)
        self.save_maze.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/diskette.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_maze.setIcon(icon1)
        self.save_maze.setIconSize(QtCore.QSize(24, 24))
        self.save_maze.setObjectName("save_maze")
        self.verticalLayout.addWidget(self.save_maze)
        self.load_maze = QtWidgets.QToolButton(self.centralwidget)
        self.load_maze.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/folder.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load_maze.setIcon(icon2)
        self.load_maze.setIconSize(QtCore.QSize(24, 24))
        self.load_maze.setObjectName("load_maze")
        self.verticalLayout.addWidget(self.load_maze)
        self.set_coordinate = QtWidgets.QToolButton(self.centralwidget)
        self.set_coordinate.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/coordinate.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.set_coordinate.setIcon(icon3)
        self.set_coordinate.setIconSize(QtCore.QSize(24, 24))
        self.set_coordinate.setObjectName("set_coordinate")
        self.verticalLayout.addWidget(self.set_coordinate)
        self.solve_maze = QtWidgets.QToolButton(self.centralwidget)
        self.solve_maze.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(
            ":/icons/icons/problem-solving.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.solve_maze.setIcon(icon4)
        self.solve_maze.setIconSize(QtCore.QSize(24, 24))
        self.solve_maze.setObjectName("solve_maze")
        self.verticalLayout.addWidget(self.solve_maze)
        self.generate_gif = QtWidgets.QToolButton(self.centralwidget)
        self.generate_gif.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(
            ":/icons/icons/gif-file-format-symbol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.generate_gif.setIcon(icon5)
        self.generate_gif.setIconSize(QtCore.QSize(24, 24))
        self.generate_gif.setObjectName("generate_gif")
        self.verticalLayout.addWidget(self.generate_gif)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.img = MyQLabel(self, self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img.sizePolicy().hasHeightForWidth())
        self.img.setSizePolicy(sizePolicy)
        self.img.setText("")
        self.img.setObjectName("img")
        self.gridLayout.addWidget(self.img, 0, 1, 1, 1)
        MazeGenerator.setCentralWidget(self.centralwidget)

        self.retranslateUi(MazeGenerator)
        QtCore.QMetaObject.connectSlotsByName(MazeGenerator)

    def retranslateUi(self, MazeGenerator):
        _translate = QtCore.QCoreApplication.translate
        MazeGenerator.setWindowTitle(
            _translate("MazeGenerator", "Maze Generator"))
        
    def get_points(self, points: list):
        self.getPointsClicked.emit(points[0], points[1])