# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt\maze_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_DialogSetting(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(236, 223)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.height_maze = QtWidgets.QSpinBox(Dialog)
        self.height_maze.setMinimum(2)
        self.height_maze.setMaximum(1000)
        self.height_maze.setProperty("value", 2)
        self.height_maze.setObjectName("height_maze")
        self.verticalLayout.addWidget(self.height_maze)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.width_maze = QtWidgets.QSpinBox(Dialog)
        self.width_maze.setMinimum(2)
        self.width_maze.setMaximum(1000)
        self.width_maze.setObjectName("width_maze")
        self.verticalLayout.addWidget(self.width_maze)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.image_name = QtWidgets.QLineEdit(Dialog)
        self.image_name.setObjectName("image_name")
        self.verticalLayout.addWidget(self.image_name)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.select_extension = QtWidgets.QComboBox(Dialog)
        self.select_extension.setObjectName("select_extension")
        self.select_extension.addItem("")
        self.select_extension.addItem("")
        self.verticalLayout.addWidget(self.select_extension)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout.addWidget(self.ok_btn)
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings Maze"))
        self.label.setText(_translate("Dialog", "Height maze:"))
        self.label_2.setText(_translate("Dialog", "Width maze:"))
        self.label_3.setText(_translate("Dialog", "Image name"))
        self.label_4.setText(_translate("Dialog", "Extension image"))
        self.select_extension.setItemText(0, _translate("Dialog", "PNG"))
        self.select_extension.setItemText(1, _translate("Dialog", "JPG"))
        self.ok_btn.setText(_translate("Dialog", "OK"))
        self.cancel_btn.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
